namespace SharpPlot.Utils
{
    public enum Color
    {
        Black=0,
        Red,
        Green,
        Blue,
        Yellow,
        Orange,
        Purple,
        Brown,
        Pink,
        White,
        Grey,
        RoyalBlue,
        GoldenRod,
        SteelBlue,
        Orchid,
        Aquamarine,
        Turquoise,
        Gold,
        Navy,
        SkyBlue,
        Cyan,
        Magenta,
        Coral,
        Salmon,
        Khaki,
        Beige,
        Olive,
        Plum,
        SeaGreen
    }
}